blog/urls.py
from django.urls import path

from blog import views

app_name = 'blog'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:post_id>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
]

mysite2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include('blog.urls'))
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


# Create your models here.
class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=100)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, default=None, null=True)
    body = models.TextField()
    published = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)

    class Meta:
        ordering = ['-published']
        indexes = [
            models.Index(fields=['-published'])
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('blog:post_detail', args=[self.id])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=25)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created'])
        ]

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

blog/forms.py
from django import forms

from blog.models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25, widget=forms.TextInput(attrs={'class': 'form-control'}))
    to = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    comments = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'form-control'}))


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

blog/views.py
from django.core.mail import send_mail
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404

from blog.forms import EmailPostForm
from blog.models import Post


# Create your views here.
def post_list(request):
    page_number = request.GET.get('page', 1)
    page_list_query = Post.objects.filter(status=Post.Status.PUBLISHED)
    paginator = Paginator(page_list_query, per_page=3)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'posts': posts})


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    return render(request, 'blog/post/detail.html', {'post': post})


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{data['name']} 님이 {post.title}을(를) 추천합니다."
            message = f"{post.title}을 {post_url}에서 읽어보세요.\n\n" \
                      f"{data['name']}님의 의견: {data['comments']}"
            send_mail(subject, message, 'jungman82@gmail.com', [data['to']])
            sent = True
    else:
        form = EmailPostForm()

    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})

blog/templates/blog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}base.html{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<body>
<nav class="navbar bg-body-emphasis">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Django Blog</a>
    </div>
</nav>

<div class="container gy-5">
    <div class="row">
        <div class="col-9">
            {% block content %}
            {% endblock content %}
        </div>
        <div class="col-3 text-bg-light">
            <h2>Sidebar</h2>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/pagination.html
<br>
<div class="d-flex justify-content-center">
    <ul class="pagination">
        {% if page.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ page.previous_page_number }}">Previous</a></li>
        {% endif %}
        {% for p in page.paginator.page_range %}
            <li class="page-item"><a class="page-link" href="?page={{ p }}">{{ p }}</a></li>
        {% endfor %}
        {% if page.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}">Next</a></li>
        {% endif %}
    </ul>
</div>

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">{{ post.title }}</h5>
            <p class="card-text">
                {{ post.body|linebreaks }}
            </p>
            <a href="{% url "blog:post_share" post.id %}" class="card-link">Share</a>
            <a href="#" class="card-link">Another link</a>
        </div>
    </div>

{% endblock content %}

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>LIST</h1>

    <ul class="list-group">
        {% for post in posts %}
            <li class="list-group-item">
                <a class="fs-3" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                <p>
                    {{ post.body|truncatewords:30 }}
                </p>
            </li>
        {% endfor %}
    </ul>
    {#   CBV의 경우 posts 대신 page_obj 사용 #}
    {% include 'blog/pagination.html' with page=posts %}

{% endblock content %}

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>{{ post.title }}</h1>
    {% if sent %}
        <p>
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
        </p>
    {% else %}
        <form method="post" class="container">
            <div class="row my-2">
                {{ form.name.label_tag }}
                {{ form.name }}
            </div>
            <div class="row my-2">
                {{ form.to.label_tag }}
                {{ form.to }}
            </div>
            <div class="row my-2">
                {{ form.comments.label_tag }}
                {{ form.comments }}
            </div>

            {% csrf_token %}
            <div class="row my-2">
                <input type="submit" value="Send e-mail" class="btn btn-primary">
            </div>
        </form>
    {% endif %}
{% endblock content %}